### PR TITLE
add Power VS to the infra crd definition

### PR DESCRIPTION
**Pull request by clnperez**
Signed-off-by: Christy Norman <christy@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by clnperez** [comment]
@Prashanth684 -- can you make sure I didn't miss anything?

**Comment by Prashanth684** [comment]
so along with https://github.com/openshift-powervs/api/pull/1 there are some deepcopy files missing that you need to run the code to generate

**Comment by Prashanth684** [comment]
i think you need to run `hack/update-deepcopy.sh` and `hack/update-swagger-docs.sh`

**Pull request merged**
